import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Cloud, ShieldCheck } from 'lucide-react';
import { Header, Footer, ContactBand } from '@/components/site-shell';
import { CinematicHero } from '@/components/cinematic-hero';
import { SystemVisual, RackVisual } from '@/components/system-visual';
import { ProcessStory } from '@/components/process-story';
import { capabilities, programs } from '@/lib/content';

export default function HomePage(){return <><Header/><main id="main"><CinematicHero><SystemVisual/></CinematicHero>
  <section className="capabilities-intro section" id="capabilities"><div className="shell"><div className="section-label"><span>01 / The connected picture</span><span>Technology. Working together.</span></div><div className="editorial-heading"><h2 data-reveal>Connected thinking.<br/><span>Dependable technology.</span></h2><p>Great technology is never one thing. It is the infrastructure, applications, security, and people working together.</p></div><div className="capability-rail">{capabilities.map((item,i)=><Link className="capability-link" href={`/services#${item.id}`} key={item.id}><span className="mono">0{i+1}</span><h3>{item.name}</h3><p>{item.line}</p><ArrowUpRight size={22}/></Link>)}</div></div></section>
  <ProcessStory/>
  <section className="infrastructure-section section"><div className="shell"><div className="section-label"><span>02 / Infrastructure & AMC</span><span>The operational foundation</span></div><div className="infrastructure-layout"><div><h2 className="display-section" data-reveal>Built for<br/>the work.<br/><span>Ready for<br/>what&apos;s next.</span></h2><p className="section-description">From office infrastructure and networks to maintenance. Practical services for the systems your organization depends on.</p><Link href="/services#infrastructure" className="text-link">Explore infrastructure <ArrowUpRight size={18}/></Link></div><div><RackVisual/><div className="infrastructure-index">{[['01','Develop','Office infrastructure, data centers, and network execution.'],['02','Maintain','Hardware and OS support, peripheral upgrades, and multi-vendor AMC.'],['03','Operate','Network management, facility management, and CCTV maintenance.']].map(([n,title,text])=><div key={n} data-reveal><span className="mono">{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></div></div></section>
  <section className="cloud-security"><div className="shell"><div className="section-label"><span>03 / Cloud & cybersecurity</span><span>Extend. Connect. Protect.</span></div><h2 className="display-section" data-reveal>More possibility.<br/><span>Stronger boundaries.</span></h2><div className="security-architecture" aria-hidden="true"><svg viewBox="0 0 1200 260" fill="none"><g stroke="currentColor"><path d="M0 130H340L470 65H730L860 130H1200M0 170H300L470 85H730L900 170H1200M0 90H300L470 235H730L900 90H1200"/><path className="boundary" d="M600 15L750 65V155L600 245L450 155V65Z"/><path className="boundary inner" d="M600 45L710 82V142L600 210L490 142V82Z"/></g><path className="security-pulse" d="M0 130H340L470 65H730L860 130H1200" pathLength="100"/><circle cx="600" cy="128" r="5" fill="#c9f3ff"/></svg></div><div className="cloud-security-copy"><article><Cloud size={28} strokeWidth={1.2}/><div><h3>Beyond the physical.</h3><p>Cloud migration, optimization, and ongoing management across AWS, Microsoft Azure, and Google Cloud.</p><Link className="text-link light" href="/services#cloud">Cloud services <ArrowUpRight size={17}/></Link></div></article><article><ShieldCheck size={28} strokeWidth={1.2}/><div><h3>Across the environment.</h3><p>Threat monitoring, vulnerability assessments, penetration testing, and security protocol implementation.</p><Link className="text-link light" href="/services#security">Cybersecurity services <ArrowUpRight size={17}/></Link></div></article></div></div></section>
  <section className="people-section section"><div className="shell"><div className="section-label"><span>04 / Software, staffing & support</span><span>The human side of technology</span></div><div className="editorial-heading"><h2 data-reveal>Systems are powerful.<br/><span>People make them work.</span></h2></div><div className="editorial-services">{[['Software','From requirement to working application.','Custom web, mobile, and enterprise applications, with deployment and maintenance.','software'],['Staffing','The people behind your next project.','IT manpower consultancy and professional services for project needs.','support'],['Support','Continuity beyond implementation.','Dedicated service desk, customer support, and software maintenance.','support']].map(([title,line,text,id],i)=><Link key={title} href={`/services#${id}`} className="editorial-service" data-reveal><span className="mono">0{i+1}</span><h3>{title}</h3><div><h4>{line}</h4><p>{text}</p></div><ArrowUpRight size={34} strokeWidth={1.2}/></Link>)}</div></div></section>
  <section className="training-preview section"><div className="shell"><div className="section-label"><span>05 / Learning & development</span><span>Keep your skills moving</span></div><div className="training-heading"><h2 className="display-section" data-reveal>Build capability.<br/><span>Go further.</span></h2><div><p className="section-description">Hands-on training, industry-relevant knowledge, and soft-skill development for academic and career growth.</p><Link className="text-link" href="/training">Explore the programs <ArrowRight size={18}/></Link></div></div><div className="learning-tracks">{programs.map((program,i)=><Link href="/training#programs" key={program.name} className="learning-track"><span className="mono">0{i+1}</span><h3>{program.name}</h3><div className="track-line" aria-hidden="true"><i/></div><ArrowUpRight size={18}/></Link>)}</div></div></section>
  <section className="why-section section"><div className="shell"><div className="section-label"><span>06 / About Hashbay</span><span>Bangalore, India</span></div><div className="why-statement"><h2 data-reveal>Focused on the project.<br/><span>Connected to the bigger picture.</span></h2><div><p>Hashbay Technology Private Limited is an IT manpower consultancy and professional services firm headquartered in Bangalore.</p><p>Our service commitment brings project success, people, processes, and systems into the same conversation. Delivered on-site or off-site, for projects of any size.</p><Link className="text-link" href="/about">Meet Hashbay <ArrowUpRight size={18}/></Link></div></div><div className="principle-strip"><span>Project-focused</span><span>On-site or off-site</span><span>People. Process. Systems.</span></div></div></section><ContactBand/>
  </main><Footer/></>;}
