export const capabilities = [
  { id: 'infrastructure', name: 'Infrastructure', line: 'A working foundation for your organization.', description: 'Office infrastructure, data centers, networks and the hardware behind everyday operations.', context: 'From establishing an office environment to upgrading an existing network, Hashbay brings together infrastructure development, implementation and maintenance.', need: 'Establish or upgrade your IT environment', items: ['Office infrastructure and data center development', 'Network study, design and execution', 'Network management and administration', 'System and peripheral upgrades', 'CCTV installation and maintenance'], related: 'support' },
  { id: 'cloud', name: 'Cloud', line: 'From migration to ongoing management.', description: 'Migration, optimization and management across AWS, Microsoft Azure and Google Cloud.', context: 'Cloud work does not end at migration. Hashbay supports the move to cloud environments, their optimization and their ongoing management.', need: 'Move workloads to the cloud', items: ['Cloud migration', 'Cloud environment optimization', 'Ongoing cloud management', 'AWS, Microsoft Azure and Google Cloud services'], related: 'security' },
  { id: 'security', name: 'Cybersecurity', line: 'Understand risk. Strengthen protection.', description: 'Threat monitoring, vulnerability assessment, penetration testing and security implementation.', context: 'Understand weaknesses in your technology environment and address the measures that protect it. Hashbay provides assessment, testing, monitoring and security protocol implementation.', need: 'Assess and strengthen your security', items: ['Threat monitoring', 'Vulnerability assessments', 'Penetration testing', 'Security protocol implementation'], related: 'infrastructure' },
  { id: 'software', name: 'Software development', line: 'Applications shaped around requirements.', description: 'Custom web, mobile and enterprise applications, from requirements to maintenance.', context: 'Translate business requirements into software. Hashbay works across requirement analysis, custom development, deployment and the maintenance of web, mobile and enterprise applications.', need: 'Develop or maintain a business application', items: ['Requirement analysis', 'Custom web and mobile applications', 'Enterprise application development', 'Software implementation and deployment', 'Application maintenance'], related: 'professional-services' },
  { id: 'professional-services', name: 'Professional services', line: 'Connect project needs with people.', description: 'IT manpower consultancy, staffing and professional services for on-site and off-site work.', context: 'Technology delivery also depends on people. Hashbay provides IT manpower consultancy and professional services to support project requirements and operational needs, with on-site and off-site engagement.', need: 'Bring IT expertise into a project', items: ['IT manpower consultancy', 'IT staffing', 'Technology consulting and professional services', 'On-site and off-site project support'], related: 'software' },
  { id: 'support', name: 'Support & maintenance', line: 'Attention to the systems you depend on.', description: 'Annual maintenance, hardware and OS support, facility management and service desk.', context: 'Maintain the technology already in use. Hashbay offers annual maintenance and operational support across hardware, operating systems, networks and software, alongside customer support and service desk services.', need: 'Support the technology already in place', items: ['Hardware and OS support under AMC', 'Multi-vendor annual maintenance support', 'Facility Management Services', 'Customer support and service desk', 'Software implementation and maintenance'], related: 'infrastructure' },
] as const;

export const stages = [
  { name: 'Plan', heading: 'Start with the right questions.', text: 'Connect project requirements with people, processes, and systems. Establish the scope of the technology work ahead.', detail: 'Consulting / Requirements / Network study' },
  { name: 'Build', heading: 'Give the plan a working foundation.', text: 'Bring infrastructure, networks, cloud environments, and custom software into operation around defined project needs.', detail: 'Infrastructure / Cloud / Software' },
  { name: 'Secure', heading: 'Strengthen what your business relies on.', text: 'Identify vulnerabilities, monitor threats, test defenses, and implement security protocols across your environment.', detail: 'Assessment / Testing / Threat monitoring' },
  { name: 'Support', heading: 'Keep the work moving forward.', text: 'Support the systems and the people using them through service desk, maintenance, and professional services.', detail: 'Service desk / AMC / Staffing' },
] as const;

export const programs = [
  { name: 'Cyber Security', category: 'Security', description: 'Understand threats. Build the skills to address them.', topics: ['Security fundamentals and threat mitigation', 'Practical tools including Wireshark'] },
  { name: 'Data Science', category: 'Development', description: 'Turn data into analysis, models, and understanding.', topics: ['Data analysis, visualization, and predictive modeling', 'Python, R, SQL, Tableau, and Power BI'] },
  { name: 'Azure Cloud Computing', category: 'Infrastructure', description: 'Develop a practical foundation in Microsoft Azure.', topics: ['Azure fundamentals, virtual machines, databases, and services', 'Certification preparation'] },
  { name: 'Computer Hardware & Networking', category: 'Infrastructure', description: 'Get closer to the systems behind everyday technology.', topics: ['Hardware basics and troubleshooting', 'Network setup, configuration, and maintenance'] },
  { name: 'Web Development', category: 'Development', description: 'Build for the web, from interfaces to full-stack applications.', topics: ['HTML, CSS, JavaScript, and React', 'Full-stack application development'] },
  { name: 'Network Security', category: 'Security', description: 'Explore the technologies that protect connected environments.', topics: ['Firewalls and virtual private networks (VPNs)', 'Intrusion detection and prevention systems (IDS/IPS)'] },
] as const;
